### ISSUE TITLE
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Failed to start Language Worker Channel for language :python. System.Diagnostics.Process: Cannot allocate memory.

### ISSUE THREAD

**Issue by sachidanand** [Azure/azure-functions-python-worker#390]
Hi,
   We are getting the below error in all the Python Azure Function..
Could you please let me know fix for this...
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Failed to start Language Worker Channel for language :python. System.Diagnostics.Process: Cannot allocate memory.

**Comment by maiqbal11** [comment]
Hi @sachidanand, could you provide more information about your scenario and what plan you're running on (Consumption or App Service)?

**Comment by priyaananthasankar** [comment]
https://github.com/priyaananthasankar/parseltongue/tree/master/LDAModeling is the sample that uses gensim with Python functions and deployed successfully. Are some heavy word embeddings bundled as part of the function app? Would be great if you can share the function app contents and sizes.

**Comment by balag0** [comment]
This could be due to a bad configuration which limited the amount of memory available to the app.
More details here - https://github.com/Azure/azure-functions-python-worker/issues/394

In general you can expect to have 1.5 GB (less memory taken by the functions runtime) , so if your function app memory profile exceeds that limit you will still be getting Out of memory errors (after the config fix). Currently due to the bad configuration, we are running with < 1GB memory. We expect to have the fix deployed sometime next week. 
It might be helpful for you to identify the memory profile for your app so it can work with the ~1.5GB limit.

**Comment by ygpark80** [comment]
We are having a similar problem using Consumption plan. Any updates on this issue?

**Comment by balag0** [comment]
The fix for this issue will start deploying next Monday.

**Comment by mhelb** [comment]
Is there an ETA as to when this change will be fully deployed?  I'm still experiencing the same error.

**Comment by balag0** [comment]
We are starting the deployment to stage / test regions tomorrow (5/14) and will proceed to prod regions over the next few days. We expect to have most if not all regions deployed by end of the week,
We apologize for the inconvenience.

**Comment by balag0** [comment]
Update - The updated memory config is available in East Asia now. It will be deployed to rest of the regions tomorrow.

**Comment by mhelb** [comment]
Thanks for the work fixing this, my function is working again.

**Comment by itshemant09** [comment]
@balag0 : is it deployed globally now ?

**Comment by balag0** [comment]
Yes. The deployment is complete.

**Comment by thedoupub** [comment]
Hello there 
I still get that 
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Failed to start Language Worker Channel for language :python. System.Diagnostics.Process: Cannot allocate memory.
WestEU consumption plan.

**Comment by yossie17** [comment]
you need to remove from configuration **FUNCTIONS_WORKER_RUNTIME_VERSION** and it resolve your problem.

**Comment by shlomif83** [comment]
you need to remove from configuration FUNCTIONS_WORKER_RUNTIME_VERSION and it resolve your problem.

**Comment by balag0** [comment]
Please open new issue since this is more than a year old.
