### ISSUE TITLE
Python Dependency issue: Issues installing opencv

### ISSUE THREAD

**Issue by nkma1989** [Azure/azure-functions-python-worker#497]
Hello.

I'm having issues installing opencv. I'm publishing my function through the CLI using the following command:

```
func azure functionapp publish testPSA2 --build-native-deps
```
The publishing is not a problem and it worked just fine a couple of months ago, but when I got back to the project to make some changes I get the following error when running the function:

```
2019-05-07T08:11:27.146 [Error] Executed 'Functions.processImageEvent' (Failed, Id=316890eb-95ed-4eda-8ed4-b1136a758b1c)
Result: Failure
Exception: ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
Stack:   File "/home/site/wwwroot/worker_venv/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 203, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/home/site/wwwroot/worker_venv/lib/python3.6/site-packages/azure/functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/site/wwwroot/processImageEvent/__init__.py", line 3, in <module>
    import cv2
  File "/home/site/wwwroot/worker_venv/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
```

My requirements.txt looks the following:

```
asn1crypto==0.24.0
azure-common==1.1.17
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.5
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
azure-nspkg==3.0.2
azure-storage-blob==1.4.0
azure-storage-common==1.4.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.5
grpcio==1.14.2
grpcio-tools==1.14.2
idna==2.8
numpy==1.15.4
opencv-python==3.4.5.20
protobuf==3.6.1
pycparser==2.19
python-dateutil==2.7.5
requests==2.21.0
scipy==1.2.0
six==1.12.0
urllib3==1.24.1
```

I have posted a similar issue here, deploying jobs to a GPU cluster using Azure ML SDK:
https://github.com/Azure/MachineLearningNotebooks/issues/252#issuecomment-478838718

Have anyone encountered a fix? if so please let me know. The opencv package is critical to a lot of my algorithms.

Best Regards 
Niels

**Comment by maiqbal11** [comment]
@ahmelsayed, do we have this particular dependency (`libgthread`) in our Docker image? If not, would we able to add it?

**Comment by anthonychu** [comment]
#493 is related and that particular issue can be solved by installing gcc.

**Comment by hnky** [comment]
Hi Team
Would be great to have this fixed! Any timeline available?
Henk

**Comment by osoftware** [comment]
I also need OpenCV working.

**Comment by guilhermesurek** [comment]
I'm having the same issue working with azure webapp deploying in a Linux environment, Is there any update?

**Comment by S00160602** [comment]
Has there been a soultion to this error yet?

**Comment by JerryNixon** [comment]
Any information would be nice. @InternDan

**Comment by InternDan** [comment]
Haven't found a solution yet, sorry guys. I ended up building a full blown API instead.

**Comment by MahadevanAlagar1978** [comment]
Any timelines, as we too experiencing the same issues.
Ended up hosting as API in IaaS VM, the olden days of resolution!

**Comment by horihiro** [comment]
Maybe, you need to use a custom container which installation of libopencv-dev is described in the dockerfile.

**Comment by S00160602** [comment]
I ended up using the API option aswell , tried the docker solution but it has its own problems

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sagar027** [comment]
Hi - running OpenCV for one of our partner's solutions in Azure functions and they are also blocked due to this scenario. Is there is a solution to run OpenCV in Python Azure Functions please?
Appreciate guidance.

**Comment by themaxx75** [comment]
I'm in the same boat. Can we realistically hope for a resolution soon?

**Comment by PMoneda** [comment]
Hi guys,
I found a solution by using a Docker Image with pre installed opencv in Function App.
I created a public docker image (https://cloud.docker.com/repository/docker/pmoneda/azure-functions-python-opencv) that extends default image from FunctionApps

My Dockerfile that I use to build this image is here
https://gist.github.com/PMoneda/24ca29bc7599cd4808ae98e6e3ac2489

**Comment by horihiro** [comment]
MY **unofficial** temporal workaround is followings and the sample is [here](https://github.com/horihiro/azure-functions-python-opencv-example):

  1. Copy SO libraries to your Azure Functions projects
In the sample, you can copy `libglib-2.0.so.0` and `libgthread-2.0.so.0`, which are required SO libraries for `opencv-python-headless`, by executing `retrieve_so.sh` 
  1. Change your code (it's not cool 👎 )
Instead of `import cv2`, use following code.
```python
import ctypes
import importlib

ctypes.CDLL('/PATH/TO/libglib-2.0.so.0')
ctypes.CDLL('/PATH/TO/libgthread-2.0.so.0')

cv2 = importlib.import_module('cv2')
```
3. Deploy your package including above code and the copied SO libraries by azure-functions-core-tools.

By this workaround, I confirmed that only following function can be used in the sample `__init__.py`.

  - cv2.imread
  - cv2.cvtColor
  - cv2.imwrite

**Comment by anirudhgarg** [comment]
Just wanted to sent an update that we are working on adding the libraries needed for OpenCV. We hope to add the libraries in the next 3-4 weeks if not earlier unless we find some unforeseen issue.

**Comment by HoLue** [comment]
Hello!

I think I have the same problem. And I also need that very urgently!!

@anirudhgarg I do not use docker containers - will your solution will help me, too?

Here is my exception when the line "import cv2" is reached:
```
Exception type: Microsoft.Azure.WebJobs.Host.FunctionInvocationException

Exception message:
Exception message: Exception while executing function: Functions.Test02FuncBlobTr <--- Result: Failure 
Exception: ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory 
Stack: File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 309, 
in _handle__invocation_request self.__run_sync_func, invocation_id, fi.func, args) File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, 
in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 426, 
in __run_sync_func return func(**params) File "/home/site/wwwroot/Test02FuncBlobTr/__init__.py", line 34, 
in main import cv2 File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/cv2/__init__.py", line 3, 
in <module> from .cv2 import *

Category: Function.Test02FuncBlobTr

LogLevel: Error
```
Hopefully there is a solution very soon!!!

**Comment by horihiro** [comment]
@HoLue 
could you please try this if you cannot use custom container?
https://github.com/horihiro/azure-functions-python-opencv-example 

I would appreciate your feedback.

**Comment by HoLue** [comment]
@horihiro Thanks for the fast answer - my local system is a Windows system. Before I will try, just my short question: Is there a chance that it may work?

**Comment by horihiro** [comment]
Yes.
But you need to install docker for windows and WSL with docker cli in order to get required files.

**Comment by anirudhgarg** [comment]
We have just deployed the following packages: libglib2.0-0; libsm6; libxext6; libxrender-dev and I have just confirmed including the opencv-python module now works. @horihiro @holue @themaxx75 @nkma1989 - all please confirm as well. Remember to include opencv-python in your requirements.txt /cc @ahmelsayed @kulkarnisonia16 @maiqbal11 @anthonychu Will close this out if some one else can confirm

**Comment by horihiro** [comment]
Thanks @anirudhgarg 

I confirmed that `opencv-python-headless` which needs less libraries than `opencv-python` works on python function app of consumption plan so it seems that `libgthread-2.0.so.0` and `libglib-2.0.so.0` are installed.

**Comment by HoLue** [comment]
@anirudhgarg Thanks!!! It works for me!!

**Comment by anirudhgarg** [comment]
Thanks @HoLue and @horihiro for confirming. I am going to close this issue out and really appreciate you folks engaging and letting us know about this.

**Comment by RahulNET** [comment]
It doesn't seem to work on Azure App Service. Still getting the same error.

"ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory"

**Comment by anthonychu** [comment]
@RahulNET For a Flask app on App Service, you should be workaround it by deploying your app in a container with the dependencies installed.

**Comment by RahulNET** [comment]
> @RahulNET For a Flask app on App Service, you should be workaround it by deploying your app in a container with the dependencies installed.

thanks anthonychu!  Do you mean Docker container?  otherwise, I tried with App Service for Linux and installed dependencies through "requirements.txt". However, OpenCV is having issues as mentioned above.

**Comment by horihiro** [comment]
Hi @RahulNET 
The problem you are facing is out of scope of Azure Functions.

The following issue's comment may help you.
https://github.com/horihiro/azure-functions-python-opencv-example/issues/2#issuecomment-565718690

\# but the repository which the above issue was filed into is not also related to App Service directly.

**Comment by yashpatel7025** [comment]
> It doesn't seem to work on Azure App Service. Still getting the same error.
> 
> "ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory"
> 
> What is the suggested solution or workaround if the code needs to be deployed with Azure App Service (for Linux and Flask API)

did you get any solution?I am also trying to use cv2 on azure app service

**Comment by horihiro** [comment]
@yashpatel7025 
The error means that the python runtime image of App Service on Linux doesn't have necessary libraries including `libgthread-2.0.so.0`.

You can install them by using following shell script as startup file.
https://docs.microsoft.com/en-us/azure/python/tutorial-deploy-app-service-on-linux-04

Please try it.

```sh
# In case of `opencv-python-headless`
# if you use `opencv-pyhon`, install `libopencv-dev` instead of `libglib2.0-0`
apt update && apt install libglib2.0-0 -y

# start command of your webapp
# https://docs.microsoft.com/en-us/azure/python/tutorial-deploy-app-service-on-linux-04#flask-startup-commands
gnicorn  --bind=0.0.0.0 --timeout 600 hello:myapp
```

**Comment by deependrasolanky** [comment]
> > It doesn't seem to work on Azure App Service. Still getting the same error.
> > "ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory"
> > What is the suggested solution or workaround if the code needs to be deployed with Azure App Service (for Linux and Flask API)
> 
> did you get any solution? I am also trying to use cv2 on azure app service, trying from last 3 days, did not get any solution.

I am also facing same issue. Please share if you found any solution.

**Comment by anirudhgarg** [comment]
@deependrasolanky are you also using app service ?

**Comment by deependrasolanky** [comment]
Yes. I am using app service Linux.

**Comment by anirudhgarg** [comment]
Can you try @horihiro's suggestion

**Comment by ahmelsayed** [comment]
are you using a custom image? `libglib2.0-0` should be installed on all the base images we use in app service

**Comment by deependrasolanky** [comment]
> are you using a custom image? `libglib2.0-0` should be installed on all the base images we use in app service



> Can you try @horihiro's suggestion

I tried that but while installing the package it got stuck at 'Setting up xdg-user-dirs' and container could not start.

**Comment by deependrasolanky** [comment]
> are you using a custom image? `libglib2.0-0` should be installed on all the base images we use in app service

No I am using Azure default image only.

**Comment by saarrabo** [comment]
I tried that but while installing the package it got stuck at 'Setting up xdg-user-dirs' and container could not start.

> > are you using a custom image? `libglib2.0-0` should be installed on all the base images we use in app service
> 
> > Can you try @horihiro's suggestion
> 
> I tried that but while installing the package it got stuck at 'Setting up xdg-user-dirs' and container could not start.

I am facing the same issue. Is there a fix for this issue ?

**Comment by ahmelsayed** [comment]
Can you please open another issue with a repro for the issue you're seeing.

**Comment by swiftinitdotcom** [comment]
I have same issue in azure app service-
from .cv2 import *
2021-12-09T06:25:04.404506492Z ImportError: libGL.so.1: cannot open shared object file: No such file or directory
2021-12-09T06:25:04.404512192Z

**Comment by swiftinitdotcom** [comment]
if I do not use opencv2 python script works

**Comment by vinayakbhanoo** [comment]
For anyone having an issue in Azure app service python app, add the following BEFORE 'import cv2' in your app.py:

from subprocess import STDOUT, check_call
import os
check_call(['apt-get', 'update'], stdout=open(os.devnull,'wb'), stderr=STDOUT)
check_call(['apt-get', 'install', '-y', 'libgl1'], stdout=open(os.devnull,'wb'), stderr=STDOUT)
check_call(['apt-get', 'install', '-y', 'libglib2.0-0'], stdout=open(os.devnull,'wb'), stderr=STDOUT)
check_call(['apt-get', 'update'], stdout=open(os.devnull,'wb'), stderr=STDOUT)


it should resolve the issue for missing package.
Although this wasn't necessary in the local windows or Linux system where the app was developed and tested, it is a required step for Azure apps.
