### ISSUE TITLE
Exception: ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by gaurcs** [Azure/azure-functions-python-worker#627]
I'm trying to run a simple python script via an Azure Function. When I run the function locally, it works fine. But when I deploy the function to Azure using Azure Pipelines, I encounter the ModuleNotFoundError for requests even though I've included the request in requirements.txt. I saw some other people ran into this issue such as [626,](https://github.com/Azure/azure-functions-python-worker/issues/626) I tried the solutions in these posts but haven't got anything to work.

I suspect that the packages installed in `.python_packages/lib/site-packages` are not being read in the Azure Portal or becuase I am using Linux & Python in "Consumption Plan".

#### Investigative information

Please provide the following:

- Function App name: TakeRateFunction

#### Repro steps

Provide the steps required to reproduce the problem:

I use the following YAML in my Azure Pipelines Build:
```
# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation. Replace 'xxx' with actual subscription and functionappname
  azureSubscription: 'xxxx'

  # Function app name
  functionAppName: 'xxxx'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/my_repo'


stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6 # Functions V2 supports Python 3.6 as of today
    - bash: |
        if [ -f extensions.csproj ]
        then
          dotnet build extensions.csproj --output ./bin
        fi
        pip install --target $(System.DefaultWorkingDirectory)/my_repo/.python_packages/lib/site-packages -r requirements.txt

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'production'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Azure Function is able to find requests locally but not on Portal.I get the following error in the portal:
```
Result: Failure
Exception: ModuleNotFoundError: No module named 'requests'
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 242, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/TakeRateFunction/update.py", line 13, in <module>
    from ..modules.take_rate_wrapper.take_rate import TakeRate
  File "/home/site/wwwroot/modules/take_rate_wrapper/take_rate.py", line 6, in <module>
    import requests
```

#### Known workarounds

I have tried Azure CLI instead of Azure Pipelines YAML and still getting the same error.

#### Contents of the requirements.txt file:

Provide the requirements.txt file to help us find out module related issues.

#### Related information

Tried these links but none of them helped so far 

* [Stackoverflow discussion on the module]( https://stackoverflow.com/questions/58860947/how-to-make-a-continuous-delivery-of-a-python-function-app-deployed-in-azure)
* [Microsoft official docs on this method of deployment](https://docs.microsoft.com/bs-latn-ba/azure/azure-functions/functions-how-to-azure-devops?tabs=python#yaml-based-pipeline)
* [Microsoft official repo on azure pipelines](https://github.com/microsoft/azure-pipelines-yaml/blob/master/templates/python-functionapp-to-linux-on-azure.yml)

**Comment by anirudhgarg** [comment]
Can you please share your requirements.txt file

**Comment by gaurcs** [comment]
Sorry for some reason, it didn't publish. Here is the requirements.txt
```
appdirs==1.4.3
asn1crypto==1.3.0
attrs==19.3.0
autoflake==1.3.1
azure-common==1.1.24
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
black==19.10b0
boto3==1.11.17
botocore==1.14.17
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
coverage==5.0.3
cryptography==2.8
docutils==0.15.2
idna==2.8
ijson==2.6.1
importlib-metadata==1.5.0
isort==4.3.21
jmespath==0.9.5
more-itertools==8.2.0
numpy==1.18.1
oscrypto==1.2.0
packaging==20.1
pandas==1.0.1
pathspec==0.7.0
pluggy==0.13.1
py==1.8.1
pycparser==2.19
pycryptodomex==3.9.7
pyflakes==2.1.1
PyJWT==1.7.1
pyOpenSSL==19.1.0
pyparsing==2.4.6
pytest==5.3.5
python-dateutil==2.8.1
pytz==2019.3
regex==2020.1.8
requests==2.22.0
s3transfer==0.3.3
six==1.14.0
snowflake-connector-python==2.2.1
snowflake-sqlalchemy==1.2.1
SQLAlchemy==1.3.13
toml==0.10.0
typed-ast==1.4.1
urllib3==1.25.8
wcwidth==0.1.8
zipp==2.1.0
```

**Comment by anirudhgarg** [comment]
@gaurcs can you also try to deploy your function app through the func cli and see if that works. If that works then we can start debugging Azure Pipelines.

**Comment by gaurcs** [comment]
The "import requests" issue got resolved from either using the func tools or the template. I am now getting the followin error 

```Exception while executing function: Functions.TakeRateFunction <--- Result: Failure Exception: NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:snowflake Stack: File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 315, in _handle__invocation_request self.__run_sync_func, invocation_id, fi.func, args) File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 434, in __run_sync_func return func(**params) File "/home/site/wwwroot/TakeRateFunction/update.py", line 47, in main take_rate_instance = TakeRate(logger=logger) File "/home/site/wwwroot/modules/take_rate_wrapper/take_rate.py", line 23, in __init__ self.df_events = create_take_rate_events() File "/home/site/wwwroot/modules/take_rate_wrapper/events_util.py", line 17, in create_take_rate_events event_df = read_events() File "/home/site/wwwroot/modules/take_rate_wrapper/events_util.py", line 77, in read_events engine = get_sf_engine() File "/home/site/wwwroot/modules/take_rate_wrapper/events_util.py", line 55, in get_sf_engine role=role, File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine return strategy.create(*args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/strategies.py", line 61, in create entrypoint = u._get_entrypoint() File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint cls = registry.load(name) File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/util/langhelpers.py", line 240, in load "Can't load plugin: %s:%s" % (self.group, name)```

It works fine locally with the command `func host start`. What could be the issue?

**Comment by gaurcs** [comment]
I am suspecting it may be due to Azure running Ubuntu and I am using Mac locally. Is there a way I can run a script that will install the proper Linux packages before my functions get invoked?

**Comment by gaurcs** [comment]
@anirudhgarg It seems like the issue is with the pip version. I found this [article](https://medium.com/hashmapinc/securely-using-snowflakes-python-connector-within-an-azure-function-45756f2ad950 ) where the author mentions that the Docker image is using an older version of pip which then is incompatible with sqlalchemy.(read the paragraph right before the subheading "The Dilemma". Is there a way to update the pip version using the function tools?

**Comment by gaurcs** [comment]
@anirudhgarg I solved my issue. To paraphrase the article mentioned below, the probable was likely due to the sqlalchemy extension for Snowflake that I was using, and it did work locally, it did not install properly when the service was published to Azure. It may be because of Azure maintained base Docker image not updating to the latest version of pip, which would download the appropriate version of the connector.

**Comment by stefanlenoach** [comment]
@gaurcs It's not clear exactly what you did to resolve your issue. Did you just have to update your pip version or something else?

**Comment by gaurcs** [comment]
@stefanlenoach I published my functions with a remote build option with this command:

`func azure functionapp publish my_package --build remote`

In my requirements.txt I had a package called `sqlalchemy-snowflake`. Now, the pip version used by Azure's Dockerfile is probably using an older version of pip. In my local, I am using pip 20.0.2 while the Azure's remote build is using 19.2.3. During my build it even gives me the following error:

` You are using pip version 19.2.3, however version 20.0.2 is available.` 

So I removed sqlalchemy-snowflake and it removed the error for me. So check match your local pip version and see if you  still get the same error.

**Comment by ebrucucen** [comment]
I have the same error message, whereas my local deployment is perfectly fine. I am afraid I can't see how the suggested solution `func azure functionapp publish my_package --build remote` will solve the problem as we can't run this as part of yaml .

**Comment by Peder2911** [comment]
Hey!

I am having a similar problem.

Trying to publish my function(s) through DevOps, but the functions that try importing external deps wont' serve (500 error). Reading the logs on DevOps, i can see that the dependencies are installed just fine(?), but they are not available from function code (although Azure is, so only my own dependencies are unavailable).

azure-pipelines.yml:
`
# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: SUB

  # Function app name
  functionAppName: 'cfcheck'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
        fi
      workingDirectory: $(workingDirectory)
      displayName: 'Build extensions'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6 # Functions V2 supports Python 3.6 as of today

    - script: pip3.6 install --upgrade pip setuptools wheel
      displayName: "Install package tooling"

    - script: pip3.6 install -r requirements.txt
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
`

Requirements.txt:
`
azure-functions
pandas==1.0.1
Jinja2==2.11.2
xlrd==1.2.0
`

**Comment by Peder2911** [comment]
Nevermind, fixed this by making pip install to WD/.python_packages...

**Comment by BanRahul0917** [comment]
I was using Visual Studio to publish my code to Azure Function and facing the same error for any library other than azure-functions and logging.
@gaurcs So if the python script that I am trying to run in Azure Function is __init__.py, Should I be run func azure functionapp publish __init__.py --build remote in the terminal?

**Comment by tomasslivka** [comment]
I have lost few hours with this issue and I have found that this happens when you select Python 3.7/3.8 during the function creation in Azure and later you are trying to integrate the Azure Pipeline which supports Python 3.6 only. So this is not a bug, but it's really difficult to realize the root cause if you have created your function a time ago.  I guess that Python 3.6 Azure Pipeline has different directory structure than Azure Function for Python 3.7/3.8 expects so site packages are not found. Maybe some note in the docs or check for the version of the target function would help further investigators.

**Comment by parixitgautam** [comment]
I performed the similar steps suggested above but I was receiving same issue for regex module
 
_Exception while executing function: Functions.summarize Result: Failure
Exception: ModuleNotFoundError: No module named 'regex._regex'
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/_

The regex module is present in the .python_packages/lib/site-packages

**Comment by parixitgautam** [comment]
> Nevermind, fixed this by making pip install to WD/.python_packages...

@Peder2911 hi can you mention what was the exact pip install command you made change. running into similar issue

**Comment by Peder2911** [comment]
Sure, i made pip install to $(wd)/.python_packages. This makes the packages available to anything running from wd.

**Comment by Peder2911** [comment]
I'm not sure if this is intended, or if it is a hack, but it works for me!

**Comment by anirudhgarg** [comment]
This is not a hack. If for some reason you are not able to use Remote Build then this is the right way to include your dependencies. https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#custom-dependencies

**Comment by Peder2911** [comment]
Oh ok, that's good to know! Thank you for your message. I read those docs so many times, i can't believe i missed that. 

P

**Comment by Peder2911** [comment]
Although i think the docs might be worded a bit differently: From what it says now it seems like including deps. in the .python_packages dir is only relevant when you want to include dependencies that are not publicly available (e.g not on pip), but all of my dependencies are on pip.

**Comment by antopolskiy** [comment]
Had the same issue, can confirm that changing `pip install -r requirements.txt` line in my YAML file to `pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt` resolved it.

**Comment by jfreeland** [comment]
I'm running into this problem using runtime `4.0.1.16815`.

I've tried:
```bash
az functionapp config set --subscription <sub> --name <app> --resource-group <rg> --linux-fx-version "python|3.7"
az functionapp config set --subscription <sub> --name <app> --resource-group <rg> --linux-fx-version "python|3.8"
az functionapp config set --subscription <sub> --name <app> --resource-group <rg> --linux-fx-version "python|3.9"

func azure functionapp publish <app> --subscription <sub> --build remote
func azure functionapp publish <app> --subscription <sub> --build local
func azure functionapp publish <app> --subscription <sub> --build-native-deps
pip install --target=".python_packages/lib/site-packages" -r requirements.txt && func azure functionapp publish <app> --subscription <sub> --no-build
```

I've built and run locally from the same code on Mac and Linux.  I've tried switching my local python version with `asdf local python 3.8.12` and `asdf local python 3.9.1` then `python -m venv venv && source venv/bin/activate && pip install -r requirements.txt`.  I've tried removing version pinning from my `requirements.txt`.

I haven't tried downgrading my runtime to `v3` yet.. I guess I'll do that tomorrow and retry?

**Comment by cmasch** [comment]
Hi Joey,
do you use Terraform for deploying the function app? I guess so :)
Could you pls try out to create a function app via the portal with Python as runtime? If you publish the app again, do you get some outputs about pip and installing dependencies?

If you use Terraform, could you provide the Terraform code and the provider version?
Maybe the Python runtime is not specified in the app settings (see azurerm_function_app).
**That should fix the issue:** https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_worker_runtime

Best
Christopher

**Comment by jfreeland** [comment]
Thanks @cmasch.  You were spot on.  I missed this gem, `FUNCTIONS_WORKER_RUNTIME` in my terraform `app_settings` definition, but I had it in my `local.settings.json` and skimmed right past it in the terraform docs.  For anyone else that may stumble upon this, this worked for me:

```terraform
resource "azurerm_app_service_plan" "myPlan" {
  name                = "plan"
  location            = data.azurerm_resource_group.myGroup.location
  resource_group_name = data.azurerm_resource_group.myGroup.name
  kind                = "Linux"
  reserved            = true

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "myApp" {
  name                       = "app"
  location                   = data.azurerm_resource_group.myGroup.location
  resource_group_name        = data.azurerm_resource_group.myGroup.name
  app_service_plan_id        = azurerm_app_service_plan.myPlan.id
  storage_account_name       = azurerm_storage_account.myStorageAccount.name
  storage_account_access_key = azurerm_storage_account.myStorageAccount.primary_access_key
  os_type                    = "linux"
  version                    = "~4"

  app_settings = {
    EVENTHUB_CONNECTION_STRING = azurerm_eventhub_namespace_authorization_rule.myListener.primary_connection_string
    FUNCTIONS_WORKER_RUNTIME   = "python"
  }

  site_config {
    linux_fx_version = "python|3.8"
  }
}
```

```bash
func azure functionapp publish <app> --subscription <sub> --build remote
```

And there was a very clear difference in the build output:
```bash
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201015.1, Commit: 1a35fbce482b20b71290f3a837a3469803ce4b44, ReleaseTagName: 20201015.1

Build Operation ID: |TXpug4loFB4=.998f55b_
Repository Commit : d1906ea77cca4f2d87244a0cf1398b03

Detecting platforms...
Detected following platforms:
  python: 3.8.12
Version '3.8.12' of platform 'python' is not installed. Generating script to install it...
```

**Comment by Umamahesh888** [comment]
could you please help me ASAP, quick replay is helps me a lot

**Comment by Umamahesh888** [comment]
i tried the above proccess, we are using pip 3.9 build and release succuusefully the function app, but when access through portal getting HTTP 500 error, and as per above message chains used the above command in the build pipeline, pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt, but still getting the same  HTTP response code
500 Internal Server Error could you please help me the resoling the issue. could you please help me on this, quick replay is lots of help me and thanks
<img width="640" alt="module not found" src="https://github.com/Azure/azure-functions-python-worker/assets/131890600/631f706d-660b-4c31-8266-70b6a6671f8c">

**Comment by samlaimeen** [comment]
Hi @Umamahesh888 

Could you check if your zip package contains the requests folder? If it doesn't, could you check your build pipeline and use pip install --target="./.python_packages/lib/site-packages" -r requirements.txt  for a try, since it is always working for my project based on Mircosoft doc ([Python developer reference for Azure Functions | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level&pivots=python-mode-configuration#install-local-packages)).
You can also use VSC or function core tool to do remote/local build and then deploy to azure. It will help you narrow down whether it is a build script issue or platform deploy issue.
